#pragma once

#include <spdlog/spdlog.h>

#define ENGINE_TRACE SPDLOG_TRACE
#define ENGINE_DEBUG SPDLOG_DEBUG
#define ENGINE_INFO SPDLOG_INFO
#define ENGINE_WARN SPDLOG_WARN
#define ENGINE_ERROR SPDLOG_ERROR
#define ENGINE_CRITICAL SPDLOG_CRITICAL